FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-run

ENV PULSE_SERVER=unix:/run/pulse/pulseaudio.socket
ENV PULSE_SINK=alsa_output.default

# Install dependencies for pulseaudio2 node package
RUN install_packages python pkg-config make g++ libpulse-dev
RUN curl https://www.kozco.com/tech/LRMonoPhase4.wav --silent --output test.wav

WORKDIR /usr/src
COPY . .

RUN npm install

# Run: "node play.js" or "node echo.js"
CMD [ "balena-idle" ]
