FROM balenalib/%%BALENA_MACHINE_NAME%%-debian
WORKDIR /usr/src

ENV PULSE_SERVER=unix:/run/pulse/pulseaudio.socket
ENV PULSE_SINK=alsa_output.default

RUN install_packages mplayer
RUN curl https://www.kozco.com/tech/LRMonoPhase4.wav --silent --output test.wav

# To play the file: mplayer test.wav
CMD [ "balena-idle" ]
