FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run
ENV PULSE_SERVER=unix:/run/pulse/pulseaudio.socket
ENV PULSE_SINK=alsa_output.default

WORKDIR /usr/src

COPY . .

# Install dependencies for pulseaudio2 node package
RUN install_packages python pkg-config make g++ libpulse-dev pulseaudio alsa-utils
RUN npm install

CMD while : ; do echo "${MESSAGE=Idling...}"; sleep ${INTERVAL=600}; done